#include "stm32f303xc.h"

#define SYSTEM_INIT_ERROR_FLASH 0x01
#define SYSTEM_INIT_ERROR_PLL 0X02
#define SYSTEM_INIT_ERROR_CLKSRC 0X03
#define SYSTEM_INIT_ERROR_HSI 0X04
#define SYSTEM_INIT_ERROR_FLASH
